name: frontendCI

on:

  pull_request:
    branches:
    - staging

jobs:
  staging-branch:
    name: stage-branch-pr
    runs-on: ubuntu-latest
    steps:
      - name: Stage PR Review
        uses: actions/checkout@v3
      - name: Review PR
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        id: RPR
        with:
          repo-token: ${{secrets.GIT_TOKEN}}
          event: APPROVE
          body: 'PR Approved'
      - name: Review Status
        uses: actions/checkout@v3
        run: echo "Pull Request Number - ${{ steps.cpr.outputs}}"
        #env:
          #GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
