name: frontendCI
  
on:
  workflow_dispatch:
  pull_request:
    branches:
    - staging

jobs:
  staging-branch:
    name: stage-branch-pr
    runs-on: ubuntu-latest
    steps:
      - name: Stage PR Review
        uses: actions/checkout@v3
      - name: Review PR
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        id: RPR
        with:
          repo-token: ${{secrets.GIT_TOKEN}}
          event: APPROVE
          body: 'PR Approved'
      - name: Review Status
        run: echo "Pull Request Number - $ {{ steps.RPR.outputs}}"
      - name: checkout root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create pr for main
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          source_branch: staging
          target_branch: main
          title: PR main from staging
          body: "**Automated pull request**"
