name: frontendCI
  
on:

  workflow_dispatch:

  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  dev-branch:
    name: Run-test-create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test Scripts
        run: ./udagram_tests/git_test.sh
        shell: bash
      - name: checkout root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create pr
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          source_branch: dev
          target_branch: staging
          title: Merge Dev to staging
          body: "**Automated pull request**"
         
      
 
