name: frontendCI
  
on:
  workflow_dispatch:
  pull_request:
    branches:
    - staging

jobs:
  staging-branch:
    name: stage-branch-pr
    runs-on: ubuntu-latest
    steps:
      - name: Stage PR Review
        uses: actions/checkout@v3
      - name: merge PR
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          dry-run: true
      - name: Review Status
        run: echo "Pull Request Number - ${{ steps.RPR.outputs}}"
      - name: checkout root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create pr for main
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          source_branch: staging
          target_branch: main
          title: PR main from staging
          body: "**Automated pull request**"
