name: frontendCI

on:

  push:
    branches: dev

jobs:
  dev-branch:
    name: dev-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check dev branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'devs'
      - name: check stage branch
        uses: actions/checkout@v3
        with:
          ref: 'stagings'
      - name: check-main
        uses: actions/checkout@v3
        with:
          ref: 'main'
        #env:
          #GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
